### ISSUE TITLE
Shared `BaseURL` for multiple clients

### ISSUE THREAD

**Issue by kudrykv** [shal/mono#20]
This is the bug that may emerge in the future.

The `BaseURL` is the package-level variable. The library allows for creating many clients. Though, all of them would refer to the same package-level variable. Moreover, one could change it and break already initialized clients.

```go
package main

import "github.com/shal/mono"

func main() {
	firstPublic := mono.NewPublic()

	mono.BaseURL = "new-domain"
	secondPublic := mono.NewPublic()
	// implying that `new-domain` is valid thing,
	// we implicitly broke the first client
}
```

**Comment by shal** [comment]
Thanks, @kudrykv,  for your contribution!
We will fix this bug shortly.
