### ISSUE TITLE
Inconsistent API: timestamp vs time.Time

### ISSUE THREAD

**Issue by SuddenGunter** [shal/mono#27]
At the moment library handles time in two different ways: 
- [as time.Time](https://github.com/shal/mono/blob/master/personal.go#L42)
- [as int32 timestamp](https://github.com/shal/mono/blob/master/types.go#L50)
 
It's not a huge deal, but it's a little bit inconvenient in situations, when user of the library wants to use latest synced transaction time as an argument for the next `.Transactions()` call: user would need to convert timestamp to time.Time and it would be converted back to timestamp a few rows later.

I suggest to use single approach here (doesn't care which one, but personally I would prefer raw timestamp - because mono api uses it internally and we would not introduce any abstraction over it for the end user).
But, if we go with time.Time - we would need to use [something like this](https://www.yellowduck.be/posts/handling-unix-timestamps-in-json/) for time parsing in mono api responses.

@shal  what do you think?
I could implement a PR, just say what road are we going here: time.Time vs raw timestamp

**Comment by shal** [comment]
Hey, @SuddenGunter! 

I agree with you, let's use `time.Time`, it seems a bit more complex, but more idiomatic.

**Comment by vtopc** [comment]
@SuddenGunter, hi. Given example - is not the best solution. Better to use anonymous embedding, so it will inherit all `time.Time` methods. I have even made a library for that - https://github.com/vtopc/epoch
